### ISSUE TITLE
Breaks user profile & community homepage icon & banner layout

### ISSUE THREAD

**Issue by lemmygod** [howdy-tsc/LemmyTools#12]
Browser: Firefox 114.0.2 (64-bit)

I've tested this on multiple profiles and communities

### Community screenshots

With compact old reddit theme by mershed_perderders

![image](https://github.com/howdy-tsc/LemmyTools/assets/137420192/3dc0d0c5-760b-460c-a5ad-9626aab0497a)

Without it:

![image](https://github.com/howdy-tsc/LemmyTools/assets/137420192/603839ac-967d-49ac-86ab-d04494b54202)

### Profile screenshot

![image](https://github.com/howdy-tsc/LemmyTools/assets/137420192/f3ca672d-8dca-42e4-849c-890ca339bc04)

**Comment by howdy-tsc** [comment]
Gotcha, I noticed this too with the old.reddit theme... Clearing your cache and reloading may fix the issue. I will look into this. Thanks for all your reports. I'm going to leave them open for further investigation.

**Comment by howdy-tsc** [comment]
Problem has been identified and resolved. Will be fixed in 0.1.2.2 (out sometime tonight). Thank you.
