### ISSUE TITLE
[Feature Request] Open all links on new tabs

### ISSUE THREAD

**Issue by lemmygod** [howdy-tsc/LemmyTools#13]
Recommended method: add `target="blank"` and `rel="noreferrer"` to all links that are not from the same host as the one you're browsing.

**Comment by howdy-tsc** [comment]
I actually thought of this too... But if the instance you are browsing doesn't have that community then it would fail right? Doesn't the instance have to have at least one subscriber for the instance to  sync the content from the remote community? 

It's a good idea though. I'll play around with it.

**Comment by dredshep** [comment]
You may have misunderstood. I did not mean open Lemmy communities with some federation knowledge. I meant open any external link to the site you're browsing in a new tab. For example, you're on lemm.ee, you open a link to twitter, well that's external so out to a new tab it goes.

**Comment by lemmygod** [comment]
You may have misunderstood. I did not mean open Lemmy communities with some federation knowledge. I meant open any external link to the site you're browsing in a new tab. For example, you're on lemm.ee, you open a link to twitter, well that's external so out to a new tab it goes.

**Comment by howdy-tsc** [comment]
Oh... Definitely misunderstood. Yeah I can do that. I'll add a option for it.

**Comment by howdy-tsc** [comment]
This has been added into 0.2.0.0
