### ISSUE TITLE
Formatting is a bit off

### ISSUE THREAD

**Issue by csm10495** [howdy-tsc/LemmyTools#15]
Hey folks,

See: https://sh.itjust.works/c/plugins

It looks a bit like this with LemmyTools:

![image](https://github.com/howdy-tsc/LemmyTools/assets/5749838/5fd5a522-d30e-4f17-b21e-57ce0997a139)

Without, the top bar isn't cut off.

Thanks!

Version: 0.1.2.1

**Comment by csm10495** [comment]
With the plugin disabled it looks like this: 

![image](https://github.com/howdy-tsc/LemmyTools/assets/5749838/713af5b4-7fb4-47e5-a9ea-f094c7e0e2dd)

**Comment by howdy-tsc** [comment]
Yep was identified in another issue. I'm doing an offset fix for the image expansion and drag that I think is causing it. Will fix.

**Comment by howdy-tsc** [comment]
Problem has been identified and resolved. Will be fixed in 0.1.2.2 (out sometime tonight). Thank you.
