### ISSUE TITLE
Subscription title text alignment

### ISSUE THREAD

**Issue by csm10495** [howdy-tsc/LemmyTools#16]
Hey folks,

When a community has a long name the formatting looks a bit weird:

![image](https://github.com/howdy-tsc/LemmyTools/assets/5749838/c3804bc6-b6b7-4f3c-ac94-cf8c980b7e5e)

Maybe it would be better if the text on the second line was left-aligned under the previous line's text instead of under the icon as well.

**Comment by howdy-tsc** [comment]
Agreed. The formatting could be better. I'll get something worked up.

**Comment by csm10495** [comment]
I think this is basically fixed as of  0.1.2.6

![image](https://github.com/howdy-tsc/LemmyTools/assets/5749838/9970d1ba-7c96-43d4-b487-d1f05deced23)


thanks!
