### ISSUE TITLE
Hide sidebar scrollbars

### ISSUE THREAD

**Issue by csm10495** [howdy-tsc/LemmyTools#17]
Hey folks, 

Can we have an option to hide the sidebar scrollbars:

![image](https://github.com/howdy-tsc/LemmyTools/assets/5749838/00e7d9d4-fbb6-4f37-a7ce-84b5afd7dad3)

It's bugging me a bit that its there even when minimized:

![image](https://github.com/howdy-tsc/LemmyTools/assets/5749838/2cbed72f-b32f-4c9e-bdbf-6d922b1158f6)

**Comment by csm10495** [comment]
Another alternative is to instead make the scrollbars themed.. so i guess dark in dark mode. :)

**Comment by howdy-tsc** [comment]
What browser is this? I agree that is annoying! Should be a simple fix.

**Comment by csm10495** [comment]
This is in Chrome.

**Comment by howdy-tsc** [comment]
This has been added. Will push 0.1.2.2 later tonight. Thank you for the suggestion! In Firefox they were barely noticeable so it didn't bother me. I noticed them after you mentioned it. Thank you.

**Comment by csm10495** [comment]
Hey @howdy-tsc I think this problem is still there on 0.1.2.2.. its just a different scrollbar:

![image](https://github.com/howdy-tsc/LemmyTools/assets/5749838/0f6657f8-dde0-4fe7-8726-d1a306b373a7)

**Comment by howdy-tsc** [comment]
Thank you, I see it! Gosh... I got it this time. Will be fixed for real :) I use firefox and didn't notice it. There will still be the page's scrollbar but no LemmyTools Bars.
