### ISSUE TITLE
Communities in a top bar.. ala old reddit?

### ISSUE THREAD

**Issue by csm10495** [howdy-tsc/LemmyTools#18]
Would it be possible to have the content of the subscriptions slide out in a format similar to old reddit?

I find myself missing the quick navigation at the top of the page . 

No big issue if not possible, but I've been thinking about it for a bit now. 

Thanks!

**Comment by howdy-tsc** [comment]
Ohhh. Now that is a good idea... I'll look into it! 

Thank you.

**Comment by howdy-tsc** [comment]
Going to tackle this over the weekend.

**Comment by howdy-tsc** [comment]
Made some real progress on this. Still want to add a few features before releasing. I am liking this better than the sidebar already.

![Screenshot 2023-07-17 070414](https://github.com/howdy-tsc/LemmyTools/assets/137250631/5198c3b7-c8a5-4198-8898-6a171e087570)
![image](https://github.com/howdy-tsc/LemmyTools/assets/137250631/6a3ded4d-eba3-44f3-ae7a-9609b4db1d74)
