### ISSUE TITLE
Image expansion without first click to expand

### ISSUE THREAD

**Issue by csm10495** [howdy-tsc/LemmyTools#19]
It would be cool if we could drag to expand from the initial thumbnail in the regular view instead of always having to click to grow first.

**Comment by howdy-tsc** [comment]
added in the latest version :) 0.1.2.3

**Comment by csm10495** [comment]
@howdy-tsc is this working for you? It doesn't seem to work for me: 

![notworking](https://github.com/howdy-tsc/LemmyTools/assets/5749838/1adac828-61ca-494d-bb69-0cefd61d40fe)

**Comment by howdy-tsc** [comment]
Oh I see... You want from the thumbnail. You still have to expand it first. There was actually a second click before 0.1.2.3 required on the expanded image. 

Miss communication! 

Thank you!

**Comment by csm10495** [comment]
Ohh yeah! This a feature that I used to use all the time from RES on reddit. I liked being able to drag the image and have it grow from thumbnail :)
