### ISSUE TITLE
 [Feature] Add "show images" button like RES 

### ISSUE THREAD

**Issue by datWeazel** [howdy-tsc/LemmyTools#32]
RES had a feature that allowed to expand all images with a single button. Would be nice to have this here aswell.

**Comment by howdy-tsc** [comment]
I have this working will be added to next release. 0.1.2.7!

**Comment by datWeazel** [comment]
Just updated to 0.1.2.7 but sadly the button doesn't work for me. If I click it, it simply changes the text to "Hide all images" and clicking it again triggers a page reload.

**Comment by datWeazel** [comment]
Sorry doesn't seem to be an issue with the button itself. The entire script isn't loading correctly. The settings are displayed at the bottom of the page instead of the sidebar.

**Comment by datWeazel** [comment]
Doesn't work for me because my language was set to German: https://github.com/howdy-tsc/LemmyTools/issues/35

**Comment by howdy-tsc** [comment]
@datWeazel We just implemented something else that should allow it to work for all languages.
