### ISSUE TITLE
Auto expand fails in other languages than English

### ISSUE THREAD

**Issue by Lucki** [howdy-tsc/LemmyTools#35]
The current implementation fails to find any expandable nodes if the language isn't English:

https://github.com/howdy-tsc/LemmyTools/blob/111f1b8cd8e60f02380c9a54b7c2a191bb6c3cc0/lemmyTools.js#L471

E.g. German needs:

~~~ diff
- clickableImages = document.querySelectorAll('[aria-label="Expand here"]'); 
+ clickableImages = document.querySelectorAll('[aria-label="hier erweitern"]');
~~~

However, this seems like a really fragile way to do this.

**Comment by Lucki** [comment]
I've seen you comments under the various keyboard navigation scripts and those have the same problem:

~~~ diff
- const buttonText = event.code === nextPageKey ? "Next" : "Prev";
+ const buttonText = event.code === nextPageKey ? "Weiter" : "Zurück";
~~~

**Comment by howdy-tsc** [comment]
Thank you for the reports and thank you for chiming in. Right now, Manipulating the DOM objects are limited and we are using what is being given to us with lemmy-ui. Im an amateur and doing this with my limited know how and learning a lot! If anyone has a better idea than me please help out. I admittedly made the function quickly with what seemed obvious. Perhaps there is something I am overlooking to make this work without the literally query all selector being required for functionality like this.

We are doing a code clean up right now which will give me some time to pause and revaluate some functions as the script is going to look vastly different on 0.2

Thank you.

**Comment by howdy-tsc** [comment]
@csm10495 implemented a fix that looks for the classname versus the language dynamic text of the expand link. Should fix it.Thank you @csm10495!!! It's in as of 0.2.0.1
