### ISSUE TITLE
"Show All Images" Button doesn’t work in communities

### ISSUE THREAD

**Issue by Christoph-Wagner** [howdy-tsc/LemmyTools#37]
The css-classes it hooks into don’t exist there.

**Comment by howdy-tsc** [comment]
It appears it may be this simple but will play around with it. Thank you.

```
        "row align-items-center mb-3 g-3"
```
to
```
        "mb-3"
```

**Comment by howdy-tsc** [comment]
It works now... The image button shows up in random places sometimes.
