### ISSUE TITLE
Easy Subsrcibe button leads to wrong search URL if there are params or hash characters in the source URL

### ISSUE THREAD

**Issue by localhorst** [howdy-tsc/LemmyTools#4]
Example:

Home instance: lemmy.ml
Subscribe from page: https://sh.itjust.works/c/plugins#
Created subscribe URL: https://lemmy.ml/search?q=!plugins#@sh.itjust.works&type=All&listingType=All&page=1&sort=TopAll

If I remove the hash # from the url ("!plugins#@sh.itjust.works") the search results work. 
So you just need to remove some characters before creating the search result URL. 

Great plugin btw! I will try to contribute.

**Comment by howdy-tsc** [comment]
Fantastic info. The hash I believe was something new I just noticed in lemmy 0.18. I will get that implemented in the next release. Thank you!

**Comment by localhorst** [comment]
The hash is added to the URL if you open and close LemmyTools options ;).

**Comment by howdy-tsc** [comment]
Issue should be resolved with 0.1.2 that just released. Thank you.
