### ISSUE TITLE
[Feature Request] User Comments

### ISSUE THREAD

**Issue by Christoph-Wagner** [howdy-tsc/LemmyTools#42]
I miss that part from RES, and I already have some users (currently in a text-file :D) where I want to have comments for myself, but not block them.

Should be pretty straightforward, and I plan to have a look at implementing this over the weekend when I have some time again ;)

The Features in RES are: Link to the post the tag was made from, text, and colour. Display it next to the usernames.

**Comment by howdy-tsc** [comment]
Sounds great. My goal this weekend is to start working on getting a topbar with a dropdown for the communities sorta like how the old alien site had.

**Comment by howdy-tsc** [comment]
Added in 0.2.0.6 - Thank you.
