### ISSUE TITLE
The @include is a bit too broad and gets snagged on non-Lemmy sites

### ISSUE THREAD

**Issue by beesyrupfactory** [howdy-tsc/LemmyTools#47]
Thanks for creating a usability userscript for Lemmy. This is really helpful.

One report I wanted to make is that the @include statement is too broad. This causes js errors on certain websites.

`// @include      https://*`

At this juncture, it's difficult to ID all of the URLs of the various Lemmy instances that are out in the wild, but is there any way to modify this?

For example, in [Lemmy Universal Link Switcher](https://gitlab.com/azzurite/lemmy-universal-link-switcher) I can see that there is a list of instances so that the userscript only is active on lemmy instances.

I'm a lemmy.world user, so I just changed it to `// @include      https://lemmy.world/` and that seemed to work okay.

**Comment by Lucki** [comment]
The userscript manager should let you override those values, such as seen here in Violentmonkey: 
![grafik](https://github.com/howdy-tsc/LemmyTools/assets/1408843/6bc76b84-7b6d-4577-bf15-3076bed9f1f7)

**Comment by howdy-tsc** [comment]
Actually, this is an easy fix, the isLemmySite implementation wasn't working correctly since 2.0. Will fix in next update.

**Comment by howdy-tsc** [comment]
A fix has been implemented as of 0.2.0.7 thanks.
