### ISSUE TITLE
option saved gets removed if firefox set to remove cookies and storage for webpages

### ISSUE THREAD

**Issue by rezad1393** [howdy-tsc/LemmyTools#56]
I have set firefox to remove storage (cookies and local storage) for pages unless I whitelist them.
setting of this script get removed after firefox restart.

other scripts save their setting in the value section of themself (Accesable in violentmoneky addon, don't know if others call it this or not).
for example [imdb](https://github.com/Purfview/IMDb-Scout-Mod) saves its setting and they are kept and I have not whitelisted imdb.com.

can setting be kept like that addon?

**Comment by howdy-tsc** [comment]
Hey, thanks for the comment. I am moving it to an actual browser addon and that functionality will be available. I didn't know these userScript managers had that ability. That's neat. 

I am hoping to have an xpi out for install for firefox very soon and then get on the firefox addon store. It might be a week or three. For the time being, if you deselect to clear "site data" the settings will persists. I know this isn't the best answer for privacy but it's where it's at right now without spending to much time to implement that for the userScript. 

![image](https://github.com/howdy-tsc/LemmyTools/assets/137250631/b726b548-129d-4c5e-8944-d1cb966fdcc0)

**Comment by rezad1393** [comment]
addon is nice, But...
scripts is way easier to maintain and you can publish it outside of walled garden of Mozilla addon store which is limiting and you can test way easier.
 so my suggestion is to maybe carry on with script?



some mechanisms need addon but yours would be better as script.
a lot of addons (after firefox changed its internals a long time ago) are just script packages as addon.

though it is your project so you can do what you want.


if you decide yo keep script or even an addon, please remove the https://* and limit it to user-defined domains.

in vliolentmonkey (and other script managers) user can add websites that script run on.
