### ISSUE TITLE
Cannot use Craigslist with script enabled.

### ISSUE THREAD

**Issue by just-mike** [howdy-tsc/LemmyTools#8]
With the script enabled visiting https://sfbay.craigslist.org/ causes my CPU to jump from 2% up to 30% and it stays there. Memory usage increases until browser becomes unusable.

**Comment by howdy-tsc** [comment]
Noted. I have seen this behavior once or twice too. I am going to re-work how it detects the lemmy instance where it won't run anything unless it's on lemmy. I implemented it poorly. Thank you for the report. Will update back once it's fixed!

**Comment by howdy-tsc** [comment]
Issue should be resolved with 0.1.2 that just released. Thank you.

**Comment by just-mike** [comment]
Works. Thanks!
